version: '3.8'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elastic
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: password
      # LS_JAVA_OPTS: -Xmx512m -Xms512m
    volumes:
      - ./config/elastic.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      - elastic
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.3
    container_name: logstash
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./config/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5000:5000/udp
      - 9600:9600
    # environment:
      # LS_JAVA_OPTS: -Xmx512m -Xms512m
    depends_on:
      - elastic
    networks:
      - elk

networks:
  elk:
    driver: bridge
